REDDIT_CLIENT_ID='sFRo2ADPThR8ETz3FyYg_g'
REDDIT_CLIENT_SECRET='FNfiMRJX-5J7hAm4QlRIT3GB3WXkDA'
REDDIT_USERNAME='JAmerico1898'
REDDIT_PASSWORD='Caridade1#'

youtube_api_key = 'AIzaSyBUgpgBnYkWZHQ1HQpoZFYLKVlMJNbh6Ak'

"GOOGLE_API_KEY" = 'AIzaSyCIcuCY2ltNC-lv4DdKW3pldg9xKWMdxTY'
